[package]
name = "aika"
version = "0.1.0"
edition = "2021"

[profile.release]
debug = true

[dependencies]
rayon = "1.10.0"
serde = "1.0.217"
rand = "0.9.0"
rand_distr = "0.5.0"
bincode = "1.3.3"

[dev-dependencies]
criterion = { version = "0.5", features = ["html_reports", "async_tokio"] }

[[bench]]
name = "sim_bench"
harness = false