[package]
name = "aika"
version = "0.1.0"
edition = "2021"

[profile.release]
debug = true

[features]

timewarp = []
universes = ["dep:rayon"]

[dependencies]
rayon = {version="1.10.0", optional = true}
serde = {version="1.0.217"}
rand = "0.9.0"
rand_distr = "0.5.0"

[dev-dependencies]
criterion = { version = "0.5", features = ["html_reports", "async_tokio"] }
aika = { path = ".", features = ["timewarp", "universes"] }

[[bench]]
name = "sim_bench"
harness = false